from trdg.generators import GeneratorFromWikipedia
from ocr.data_loader.auto_generate_dataloader import AutoGenerateDataloader
import numpy as np

if __name__ == '__main__':
    # import cv2
    # generator = GeneratorFromWikipedia(count=100, size=64, language='ja',
    #                                    skewing_angle=2, random_skew=True, blur=1, random_blur=True,
    #                                    background_type=3, distorsion_type=-1)
    #
    # print('Start generating ...')
    # for i, (img, lbl) in enumerate(generator):
    #     img_path = './data/generated/' + str(i) + '.png'
    #     cv2.imwrite(img_path, np.array(img))
    #     # print(img_path, lbl)
    obj = AutoGenerateDataloader('./data', batch_size=16)
    for i, e in enumerate(obj):
        print(i)
