from trdg.generators import GeneratorFromWikipedia
from ocr.data_loader.auto_generate_dataloader import AutoGenerateDataloader
import numpy as np

if __name__ == '__main__':
    import cv2
    generator = GeneratorFromWikipedia(count=100, size=40, language='ja',
                                       skewing_angle=2, random_skew=True, blur=1, random_blur=True,
                                       background_type=3, distorsion_type=-1, margins=(2, 2, 2, 2))

    print('Start generating ...')
    for i, (img, lbl) in enumerate(generator):
        img_path = './data/generated/' + str(i) + '.png'
        cv2.imwrite(img_path, np.array(img))
        print(img_path, lbl)
    # obj = AutoGenerateDataloader('./data', batch_size=16)
    # for i, e in enumerate(obj):
    #     cv2.imwrite('../data/generated/' + str(i) + '.png', img)
